package mrs.domain.model.mybatis;

import java.io.Serializable;
import java.time.LocalDate;
import java.time.LocalTime;
import java.util.Objects;

import mrs.domain.model.RoleName;

public class Reservation implements Serializable {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.reservation.reservation_id
	 * @mbg.generated  Mon Jun 08 10:00:29 JST 2020
	 */
	private Integer reservationId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.reservation.start_time
	 * @mbg.generated  Mon Jun 08 10:00:29 JST 2020
	 */
	private LocalTime startTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.reservation.end_time
	 * @mbg.generated  Mon Jun 08 10:00:29 JST 2020
	 */
	private LocalTime endTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.reservation.reserved_date
	 * @mbg.generated  Mon Jun 08 10:00:29 JST 2020
	 */
	private LocalDate reservedDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.reservation.room_id
	 * @mbg.generated  Mon Jun 08 10:00:29 JST 2020
	 */
	private Integer roomId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.reservation.user_id
	 * @mbg.generated  Mon Jun 08 10:00:29 JST 2020
	 */
	private String userId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table public.reservation
	 * @mbg.generated  Mon Jun 08 10:00:29 JST 2020
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.reservation.reservation_id
	 * @return  the value of public.reservation.reservation_id
	 * @mbg.generated  Mon Jun 08 10:00:29 JST 2020
	 */
	public Integer getReservationId() {
		return reservationId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.reservation.reservation_id
	 * @param reservationId  the value for public.reservation.reservation_id
	 * @mbg.generated  Mon Jun 08 10:00:29 JST 2020
	 */
	public void setReservationId(Integer reservationId) {
		this.reservationId = reservationId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.reservation.start_time
	 * @return  the value of public.reservation.start_time
	 * @mbg.generated  Mon Jun 08 10:00:29 JST 2020
	 */
	public LocalTime getStartTime() {
		return startTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.reservation.start_time
	 * @param startTime  the value for public.reservation.start_time
	 * @mbg.generated  Mon Jun 08 10:00:29 JST 2020
	 */
	public void setStartTime(LocalTime startTime) {
		this.startTime = startTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.reservation.end_time
	 * @return  the value of public.reservation.end_time
	 * @mbg.generated  Mon Jun 08 10:00:29 JST 2020
	 */
	public LocalTime getEndTime() {
		return endTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.reservation.end_time
	 * @param endTime  the value for public.reservation.end_time
	 * @mbg.generated  Mon Jun 08 10:00:29 JST 2020
	 */
	public void setEndTime(LocalTime endTime) {
		this.endTime = endTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.reservation.reserved_date
	 * @return  the value of public.reservation.reserved_date
	 * @mbg.generated  Mon Jun 08 10:00:29 JST 2020
	 */
	public LocalDate getReservedDate() {
		return reservedDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.reservation.reserved_date
	 * @param reservedDate  the value for public.reservation.reserved_date
	 * @mbg.generated  Mon Jun 08 10:00:29 JST 2020
	 */
	public void setReservedDate(LocalDate reservedDate) {
		this.reservedDate = reservedDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.reservation.room_id
	 * @return  the value of public.reservation.room_id
	 * @mbg.generated  Mon Jun 08 10:00:29 JST 2020
	 */
	public Integer getRoomId() {
		return roomId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.reservation.room_id
	 * @param roomId  the value for public.reservation.room_id
	 * @mbg.generated  Mon Jun 08 10:00:29 JST 2020
	 */
	public void setRoomId(Integer roomId) {
		this.roomId = roomId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.reservation.user_id
	 * @return  the value of public.reservation.user_id
	 * @mbg.generated  Mon Jun 08 10:00:29 JST 2020
	 */
	public String getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.reservation.user_id
	 * @param userId  the value for public.reservation.user_id
	 * @mbg.generated  Mon Jun 08 10:00:29 JST 2020
	 */
	public void setUserId(String userId) {
		this.userId = userId;
	}

	public boolean overlap(Reservation target) {
        if (!Objects.equals(getRoomId(), target.getRoomId())) {
            return false;
        }
        if (startTime.equals(target.startTime) && endTime.equals(target.getEndTime())) {
            return true;
        }
        return target.endTime.isAfter(startTime) && endTime.isAfter(target.startTime);
    }

    public boolean enabledCancel(Usr requestUser) {
        if (requestUser.getRoleName() == RoleName.ADMIN) {
            return true;
        }
        return Objects.equals(getUserId(), requestUser.getUserId());
    }

}